### ISSUE TITLE
service is not working (ERROR: could not find datum for type sandbox_t...)

### ISSUE THREAD

**Issue by mokevnin** [eval-so/frontend#20]
{
    "stdout": "",
    "stderr": "ERROR: could not find datum for type sandbox_t\n/usr/bin/sandbox: Sandbox Policy is currently disabled.\nYou need to enable the policy by executing the following as root\n# semodule -e sandbox\n",
    "wallTime": 130,
    "exitCode": 1
}

**Comment by relrod** [comment]
Ugh, :(.

Thanks for the report - fixed.
