### ISSUE TITLE
OpenID Login

### ISSUE THREAD

**Issue by relrod** [eval-so/frontend#4]
@phuzion suggested adding OpenID login support. I can't think of a huge reason not to, Play supports this itself, and it's easy to fake a login in the UserController, when we get a valid response from the OpenID redirect (back to Frontend) -- so this would be pretty easy to implement.

This would only be used for authing to the web app, not the API, of course.

**Comment by Raynes** [comment]
What about Personas instead? I'm a big fan of BrowserID.

**Comment by awilfox** [comment]
Thing is, anyone with Google, Yahoo, WordPress, or LiveJournal already has OpenID.  That's pretty much our entire target demographic.

## 

Andrew Wilcox (sent from my iPhone)
Software architect and Corgi evangelist
Wilcox Technologies

**Comment by Raynes** [comment]
So? The signup flow for BrowserID is basically the same as the login flow. I like BrowserID because of how streamlined, simplistic and easy it is.

I don't particularly care either way, but I don't see any good reason to do OpenID and not BrowserID. I'll still use it in the end. ;)
