### ISSUE TITLE
Should we store full name or not?

### ISSUE THREAD

**Issue by relrod** [eval-so/frontend#7]
There was some discussion in Tenthbit #programming today from people who I'd asked to test the signup process out for us.

The discussion basically broke into four groups of people:
- Full name should not be stored at all, for any reason.
- Full name should be broken into two fields, first and last name
  - This was later unanimously decided bad, for accessibility reasons.
- Full name should be optional, but the field should be there.
- Full name should remain required.

So the question is: Do we want to change this behavior at all?

My thoughts on keeping the name field required are:
1. Possibly personalizing UX (though referring to people by their full name (e.g. "Hi, Ricky Elrod!") is weird.
2. Probably good to have in case any form of legal issue crops up.

I'll note though that GitHub's registration form does not have a name field at all.

Discuss.

**Comment by relrod** [comment]
// cc @CorgiDude @duckinator @ttech @Raynes @programble

**Comment by Ttech** [comment]
I think it should be a field that can be used, however it should be optional due to case of the service.

Users are not storing any information on the service. This is a debugging and evaluation system not a file or code hosting service.

Many services do not require a full name as a required field for sign up including github. pastebin.com (and clones), and many other services. These services do not have any negative UX aspects as they use the nickname to greet a user. 

The user can add their name if they so desire to further personalize their interface.

**Comment by duckinator** [comment]
I feel if you store it, it should not even be listed in the sign up page. It should be a setting that can be filled in later. This is becoming more common recently.

However, I don't think it's necessary at all. Re "legal issues," people lie about their names online _all the time,_ so it really serves less purpose than their IP would!

Some things worth noting:
1. There are people with no last names: http://en.wikipedia.org/wiki/Mononym#Countries_where_mononyms_are_normal
2. There are people who have multi-word first names (actual example: "[Riley Anne] [Marie] [&lt;last name withheld>]")
3. There are people whose surnames or equivalent go first.
4. Someone has a 746 character long name: http://en.wikipedia.org/wiki/Wolfe%2B585,_Senior

Regardless, I believe it should be _optional_ if it is there at all.

EDIT: Apparently the name "Brfxxccxxmnpcccclllmmnprxvclmnckssqlbb11116" got denied, so I removed that.

**Comment by duckinator** [comment]
In case you don't want to read through all of the mononym article, here's the key part:

_Single names still also occur in Tibet[13] and Mongolia.[citation needed] Most Afghans have no surname.[14]_

**Comment by awilfox** [comment]
I concur with Ttech.

Either way, Full Name can be optionally pulled from OpenID and it can also be pulled from Facebook ID.

Which I feel should almost universally replace the sign up form.

Andrew Wilcox (sent from my iPhone)
Software architect and Corgi evangelist
Wilcox Technologies

**Comment by relrod** [comment]
@duckinator certainly some interesting notes there, but I don't see how they're really relevant here.
1. If they don't have a last name they fill in their first name -- the field only requires that something be entered, not that it contain a space.
2. Again, we don't require only $x number of words, that name would store fine.
3. Same applies, we don't assume order anywhere.
4. We do have a length limit on the name field, as it's stored as a `varchar(255)` not a text field. However, wouldn't people with a name longer than 255 chars already be constrainted in real life anyway? How would their name fit on an envelope? etc.

Not saying that I disagree with your broad point, I just don't see the relevance of your example points.

**Comment by duckinator** [comment]
@CodeBlock it seems you're opting more for just a "Name" field than a "Full name" field now, which I certainly think is a great improvement.

Although, given the following:
1. It won't really help with legal issues (it wouldn't even if it were overly-strict, as people tend to lie about their name)
2. The only reliable method is "INSERT THE PHRASE BY WHICH YOU WOULD LIKE TO BE IDENTIFIED HERE"
3. It's for personalization only

I'm wondering if it's still worthwhile.

**Comment by relrod** [comment]
@duckinator what is your thought on pulling it in from openid when we implement that, like @CorgiDude said? Don't bother with it at all?

**Comment by duckinator** [comment]
@CodeBlock Yea, I'd say don't bother at all. Some sites address people by their username (ie, Twitter), and some simply don't address people at all and skip right to the content of the email (ie, Youtube, Moo.com, Ponoko, dotCloud). I don't think personalization is required beyond a username, for something of this sort.

EDIT: Derp. I think you meant personalization of the site, in which case I can't think of any real need for their full name, and the only service I can think of that addresses you by name on the site is LinkedIn...and I'd hope you don't use them for inspiration.

**Comment by awilfox** [comment]
@CodeBlock @duckinator I don't understand where "legal issues" come from anyway. Oh noes, someone used breakpoint to run 256-bit SSL code from Iran! How are we responsible for that anyway? We're a service provider. Just like google can't block OpenSSL in search results in Iran we can't do anything about illegal code.

Also @duckinator I think personalisation is a good thing because it makes the user more likely to use the service. Some day I'll even find the study to cite for this.

Andrew Wilcox (sent from my iPhone)
Software architect and Corgi evangelist
Wilcox Technologies

**Comment by duckinator** [comment]
@CorgiDude re "legal issues:" I agree. Unless you openly encouraged something classified as illegal I can't think of any potential legal issues.

Re personalization: but how much personalization is needed for a website _dedicated to evaluating code and barfing the results up in a pretty format?_ I'd say "not a lot."

**Comment by awilfox** [comment]
Really @duckinator? Twitter doesn't use full names? (I hope GitHub accepts email attachments)

Andrew Wilcox (sent from my iPhone)
Software architect and Corgi evangelist
Wilcox Technologies

**Comment by duckinator** [comment]
@CorgiDude apparently it's incredibly inconsistent about it. I've gotten emails starting with "duckinator," but I found one starting with "Nick Markwell" now that I poked around. Silly Twitter. :|

**Comment by duckinator** [comment]
@CorgiDude Also, it does not accept attachments. I couldn't imagine why. /sarcasm

Also, as I mentioned to @CodeBlock on IRC: another potential idea is make it optional and remove it entirely from the main signup page, then show "Hey &lt;username>, why not [edit your profile]?" or similar along the top at first login, and just use the username everywhere if no actual name is specified.

**Comment by relrod** [comment]
I kind of like @duckinator's last idea. And we could easily override User.name to return the full name if it exists, username if not.

@CorgiDude Just worried about export laws or something silly coming up one day. I should look into this more and what all is good to store for things like this. Yes, users can fake their names, but that's why there's a ToS that we (will) need to make, that says "You best not be lying to us." :P Then if they lie anyway, they're only hurting themselves in legal cases.

**Comment by awilfox** [comment]
http://cl.ly/image/3S0t1M1v0R02

I'm so glad cloud has a mobile app.

I still think this whole discussion is pointless because OpenOD and Facebook auth make sign up forms obsolete.  But if the profile only has the Name field, that seems pointless to bug the user over /one field/. Have it on the form instead of having a flash. Now if there are more fields later (I don't know what they would be), then that would make more sense.

Andrew Wilcox (sent from my iPhone)
Software architect and Corgi evangelist
Wilcox Technologies

**Comment by awilfox** [comment]
@CodeBlock I don't think export laws will come up. If you live in Iran you can still get a US VPN and circumvent ALL the things. IANAL, but again, as a service provider, liability is pretty well nil as I understand the law. The ToS could pretty well just say "you agree not to run code that would be illegal in your territory or that would break international laws" etc.

Andrew Wilcox (sent from my iPhone)
Software architect and Corgi evangelist
Wilcox Technologies

**Comment by relrod** [comment]
>  If you live in Iran you can still get a US VPN and circumvent ALL the things.

But then that's on you, not us.

**Comment by duckinator** [comment]
@CorgiDude then I vote for not having it at all. It offers only marginal personalization over their username for something of this sort.

**Comment by awilfox** [comment]
> If you live in Iran you can still get a US VPN and circumvent ALL the things.
> 
> But then that's on you, not us.
> 
> It's on them anyway. Unless we ask every user for their country and require it, and then test every code for encryption before returning a result, it /cannot/ be the fault of Breakpoint.

And then you should also inspect their code for government secrets, malware, and other illegalities. That would get insane quickly. You can't police every bit of code.

Andrew Wilcox (sent from my iPhone)
Software architect and Corgi evangelist
Wilcox Technologies

**Comment by relrod** [comment]
Ok. Seems the consensus is to at least make it optional and move the form field off of the main signup form... If GitHub can get away with it, I don't see why we can't.

Will push a fix for this soon, unless someone beats me to it.

**Comment by relrod** [comment]
Thanks for the feedback, all.
